
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DB
{

using System;
    using System.Collections.Generic;
    
public partial class OrderLine
{

    public int ID { get; set; }

    public System.Guid ClientID { get; set; }

    public System.Guid EmployeeID { get; set; }

    public int CaseID { get; set; }



    public virtual Case Case { get; set; }

    public virtual Client Client { get; set; }

    public virtual Employee Employee { get; set; }

}

}
